#你的私钥数组，系统启动后会在当前目录下生成一个PRIVATEKEY文件，里面是加密后的私钥，虽然做了加密，但是还是要小心，不要泄露，系统启动后会将此项配置删除，不在服务器上储存私钥
private_key: ""
#solana rpc url
rpc_url: "http://xxxx"
#jupiter api url
jupiter_api_url: "http://0.0.0.0:18080"
#yellowstone grpc url
yellowstone_grpc_url: "http://xxxx"
# Jito MEV-Block-Engine 节点配置列表，建议配置上多个节点，随机选择一个节点进行交易，这样的你的QPS会有提升，尽量选择几个距离你比较近的节点，当然全发也可以，目测日本较慢，会降低整体效率,如果想追求速度，那么jito的引擎只开本区域，你会起飞
jito_engine:
  - NL # 荷兰阿姆斯特丹节点
  - DE      # 德国法兰克福节点
  - NY      # 美国纽约节点
  - SLC     # 美国盐湖城节点
  - DE      # 德国法兰克福节点
  # - Tokyo   # 日本东京节点
#是否开启随机引擎，建议开启，随机引擎会随机选择一个节点进行交易，这样的你的QPS会有提升
random_engine: true
#jito配置UUID，没怎么测试，建议先不要用,使用多ip的方法，而不是配置uuid
jito_uuid: ""
#从url加载代币，可以从你的jup加载代币，你的jup加载了什么币，会拉到bot内。如果从其他地方拉取，需要和jup返回结构抱持一致，建议从jup加载代币
load_mints_form_url: "http://0.0.0.0:18080/tokens"
#从文件加载代币
intermediate_tokens_file: "test.json"
#从配置文件加载代币
intermediate_tokens:
  - "6AJcP7wuLwmRYLBNbi825wgguaPsWzPBEHcHndpRpump"
  # 排除的币种
not_support_tokens:
#最大代币数量，如果低于最大限制的60%会一直请求load_mints_form_url，直到达到目标才会运行起来，主要是为了链接jup 的时候jup还没加载好全部的代币
max_tokens_limit: 80
#最小利润阈值
min_profit_threshold: 4000
#最大tip限制，单位lamports，给jito的最大限制
max_tip_lamports: 100000000
#静态tip百分比，给jito的tip百分比
static_tip_percentage: 0.7501
#交易memo，可以不设置
memo: ""
#建议先从小的开始0.1-1s，设置很多不会影响性能，性能主要由线程和网络io决定
trade_range:
  - 100000000    # 0.1 SOL
  - 200000000    # 0.2 SOL
  - 300000000    # 0.3 SOL
  - 400000000    # 0.4 SOL
  - 500000000    # 0.5 SOL
  - 600000000    # 0.6 SOL
  - 700000000    # 0.7 SOL
#发送交易类型，建议选择Mixed，可选Rpc,Grpc,Mixed，选择Mixed可以让你的ip限制速率翻倍
rpc_type: Mixed
#blockhash rpc类型，建议选择Rpc，可选Grpc,Rpc，当前实现Grpc不是订阅的，等改成订阅的再选用Grpc
blockhash_rpc_type: Rpc

#是否开启block缓存，建议开启
blockhash_cache_enabled: true
#block缓存过期时间，单位ms，缓存1s没啥问题，降低下节点压力
blockhash_cache_ttl_ms: 1000
#性能相关，开启多少个线程,系统负载全靠这个控制
thread_count: 8
#每个线程里多少个网络IO，可以一个线程配2个左右，具体看性能，自行调试，作者也不知道多少是好的
max_concurrent: 4

#日志相关能力
log_rate_limit: false
#打印机会
log_opportunities: false
#打印交易执行
log_trade_execution: false
#是否开启单独钱包
enable_separate_wallet: true

#ip 配置信息，如果有多IP可以在这里配置，否则使用本机IP，建议配置上多IP，如果有请取消注释，并配置上
ip_addrs:
  - "xxxx"
#jup 调优
#是否只使用单跳，当前多跳还有待调整，建议现在只使用单跳
onlyDirectRoutes: true
#限制中间代币为顶级代币，建议开启，此参数也就是在多跳的时候有用，现在多跳没那么好使，先这样
restrict_intermediate_tokens: true
#是否预检交易大小，先暂时关闭，这个只对多跳有用，等待后续开发
check_transaction_size: false
#是否开启动态计算预算,建议开启
dynamic_compute_unit_limit: true
#计算预算百分比，设置这个值是因为，模拟后的cu可能偏大，可以设置百分比二次修改cu限制，近一步降低cu限制
cu_limit_percentage: 0.98
#计算预算，在开启动态预算的时候不生效
compute_unit_limit: 180000
